name: mindpeers
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # state-management  
  mobx: ^2.1.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  logger: ^1.1.0
  auto_route: ^5.0.2
  after_layout: ^1.2.0
  google_fonts: ^3.0.1
  data_channel: ^2.0.0+1
  equatable: ^2.0.5
  flutter_mobx: ^2.0.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  mobx_codegen: ^2.0.7+3
  build_runner: ^2.3.0
  json_serializable: ^6.5.2
  json_annotation: ^4.7.0
  auto_route_generator: ^5.0.2

flutter:  
  uses-material-design: true
  assets:
    - assets/images/
