name: mindpeers
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # state-management  
  mobx: ^2.1.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  logger: ^1.1.0
  auto_route: ^5.0.2
  after_layout: ^1.2.0
  google_fonts: ^3.0.1
  data_channel: ^2.0.0+1
  equatable: ^2.0.5
  flutter_mobx: ^2.0.6+4
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  data_connection_checker_nulls: ^0.0.2
  json_annotation: ^4.7.0
  cached_network_image: ^3.2.2
  vibration: ^1.7.6
  modal_bottom_sheet: ^2.1.2
  flutter_svg: ^1.1.6
  sprung: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  mobx_codegen: ^2.0.7+3
  build_runner: ^2.3.0
  json_serializable: ^6.5.2
  auto_route_generator: ^5.0.2

flutter:  
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-ThinItalic.ttf
          weight: 100
          style: italic
